Moved weights download + enhancements
AdaptiveMotorControlLab/CellSeg3d pull request #19
Opened 2022-07-09 08:24 UTC by C-Achard

- Weight download now always happens in worker thread to avoid freezing UI

- Download progress bar now shows on the log in the plugin

- Models .py files changed to be as simple as possible (so users can more easily add custom models)

2022-07-09 08:25 UTC, C-Achard commented
@MMathisLab Do you think we could check if weights are already in the folder and skip the download if they are, or should it always download the latest weights ?

2022-07-15 11:51 UTC, MMathisLab commented
>> @MMathisLab Do you think we could check if weights are already in the folder and skip the download if they are, or should it always download the latest weights ?

Yes, that would be great to do!

2022-07-15 11:52 UTC, MMathisLab approved these changes

2022-07-15 11:54 UTC, MMathisLab commented
HI @C-Achard sorry, I think this is still some miss understanding; we should not call it TRAILMAP_Pytorch, it should just be "TRAILMAP" as I had it, and TRAILMAP_MS (this is the weights we trained on our data).

2022-07-15 12:15 UTC, C-Achard commented
@MMathisLab Fixed ! Thanks for the reminder

2022-07-15 12:17 UTC, C-Achard commented
> > > @MMathisLab Do you think we could check if weights are already in the folder and skip the download if they are, or should it always download the latest weights ?
> 
> Yes, that would be great to do!

Great, I'll work on implementing that, as well as an "always update weights" toggle, I think, so this way people can update the weights they have in case we change them

2022-07-17 00:25 UTC, MMathisLab requested changes

2022-07-17 00:25 UTC, MMathisLab commented on napari_cellseg3d/models/model_TRAILMAP_MS.py
> +    # original model from Liqun Luo lab, transferred to pytorch
this note is incorrect; it should say TRAILMAP ported to PyTorch, and trained on mesoSPIM data from EPFL/Wyss

2022-07-17 00:32 UTC, MMathisLab approved these changes

2022-07-17 00:34 UTC, MMathisLab approved these changes

2022-07-17 00:39 UTC, merged