Small docs update for WNet
AdaptiveMotorControlLab/CellSeg3d pull request #68
Opened 2024-04-05 07:45 UTC by C-Achard

- [x] Change WNet to WNet3D
- [ ] Make necessary changes to WNet guide
- [ ] Rename Review to Label
- [ ] (Change WNet to WNet3D in code)

2024-04-05 07:51 UTC, MMathisLab requested changes
Small comments

2024-04-05 07:51 UTC, MMathisLab commented on docs/source/guides/detailed_walkthrough.rst
> +   * **WNet3D** is our reimplementation of an unsupervised model, which can be used to produce segmentation without labels.
It's our "extension"

2024-04-05 07:51 UTC, MMathisLab commented on docs/welcome.rst
> +* A custom re-implementation of the `WNet3D`_ by Xia and Kulis [3]_
More than a reimplementation, a new nn inspired by ...

2024-04-05 07:57 UTC, C-Achard commented on docs/welcome.rst
> +* A custom re-implementation of the `WNet3D`_ by Xia and Kulis [3]_
Thanks

2024-04-05 08:15 UTC, MMathisLab approved these changes

2024-04-05 08:28 UTC, MMathisLab commented on docs/source/guides/detailed_walkthrough.rst
> +   * **WNet3D** is our extension of an unsupervised model, which can be used to produce segmentation without labels.
I guess best here to link to "unsupervised walkthrough?"

2024-04-05 08:29 UTC, MMathisLab requested changes
small new comments

2024-04-11 20:31 UTC, MMathisLab approved these changes

2024-04-11 20:31 UTC, merged